"""add chunk_index to DocumentChunk

Revision ID: a87ec7ed2705
Revises: a43154f42e3d
Create Date: 2025-11-04 01:30:49.716949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87ec7ed2705'
down_revision: Union[str, None] = 'a43154f42e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###
